import { IExtraArtist } from './extra-artist.interface';
import { ICommunity } from './community.interface';
import { ICompany } from './company.interface';
import { IFormat } from './format.interface';
import { IIdentifier } from './identifier.interface';
import { IImage } from './image.interface';
import { IExtraLabel } from './extra-label.interface';
import { ITrack } from './track.interface';
import { IVideo } from './video.interface';

export interface IRelease {
  id: number;
  artist_sort: string;
  country: string;
  data_quality: string;
  date_added: string;
  date_changed: string;
  estimated_weight: number;
  format_quantity: number;
  genres: string[];
  lowest_price: number;
  master_id: number;
  master_url: string;
  notes: string;
  num_for_sale: number;
  released: string;
  released_formatted: string;
  resource_url: string;
  series: any[];
  status: string;
  styles: string[];
  thumb: string;
  title: string;
  uri: string;
  year: number;
  artists: IExtraArtist[];
  community: ICommunity;
  companies: ICompany[];
  extraartist: IExtraArtist[];
  formats: IFormat[];
  identifiers: IIdentifier[];
  images: IImage[];
  labels: IExtraLabel[];
  tracklist: ITrack[];
  videos: IVideo[];
}
